version: "3.8"
services:
  generator:
    build: ./generator
    ports:
      - "5003:5000"
    depends_on:
      - cache

  cache:
    build: ./cache
    ports:
      - "5001:5000"
    depends_on:
      - score

  score:
    build: ./score
    environment:
      - GEMINI_API_KEY=AIzaSyBC0SNLcwFXRobS_8IS20LUpmtUxMW0DEU
    depends_on:
      - storage


  storage:
    build: ./storage
    ports:
      - "5002:5000"
